#!/usr/bin/env python
# Autogenerated script by pseudo-generator.py
from orderedDict import OrderedDict

PSEUDO = OrderedDict()
PSEUDO["Ag"] = (
                 "Ag.pbe-d-rrkjus.UPF",
                 "Ag.pz-d-rrkjus.UPF",
                )

PSEUDO["Al"] = (
                 "Al.blyp-n-van_ak.UPF",
                 "Al.bp-n-van_ak.UPF",
                 "Al.pbe-n-van.UPF",
                 "Al.pbe-rrkj.UPF",
                 "Al.pbe-sp-van.UPF",
                 "Al.pw91-n-van.UPF",
                 "Al.pz-vbc.UPF",
                )

PSEUDO["Ar"] = (
                 "Ar.pz-rrkj.UPF",
                )

PSEUDO["As"] = (
                 "As.pbe-n-van.UPF",
                 "As.pw91-n-van.UPF",
                 "As.pz-bhs.UPF",
                )

PSEUDO["Au"] = (
                 "Au.blyp-van_ak.UPF",
                 "Au.bp-van_ak.UPF",
                 "Au.pbe-nd-rrkjus.UPF",
                 "Au.pbe-nd-van.UPF",
                 "Au.pbe-van_ak.UPF",
                 "Au.pw91-d-van.UPF",
                 "Au.pw91-van_ak.UPF",
                 "Au.pz-d-rrkjus.UPF",
                 "Au.pz-d-van.UPF",
                 "Au.pz-van_ak.UPF",
                 "Au.rel-pz-rrkjus.UPF",
                )

PSEUDO["Ba"] = (
                 "Ba.pbe-nsp-van.UPF",
                 "Ba.pw91-nsp-van.UPF",
                )

PSEUDO["B"] = (
                 "B.blyp-n-van_ak.UPF",
                 "B.bp-n-van_ak.UPF",
                 "B.pbe-n-van_ak.UPF",
                 "B.pbe-n-van.UPF",
                 "B.pw91-n-van_ak.UPF",
                 "B.pw91-n-van.UPF",
                 "B.pz-bhs.UPF",
                 "B.pz-vbc.UPF",
                )

PSEUDO["Be"] = (
                 "Be.pz-n-vbc.UPF",
                 "Be.star1s-pz-n-vbc.UPF",
                )

PSEUDO["Bi"] = (
                 "Bi.pbe-d-mt.UPF",
                )

PSEUDO["Br"] = (
                 "Br.pbe-van_mit.UPF",
                 "Br.pw91-mt.UPF",
                 "Br.pz-vbc.UPF",
                )

PSEUDO["Ca"] = (
                 "Ca.pbe-nsp-van.UPF",
                 "Ca.pw91-nsp-van.UPF",
                 "Ca.pz-n-vbc.UPF",
                )

PSEUDO["C"] = (
                 "C.blyp-mt.UPF",
                 "C.blyp-van_ak.UPF",
                 "C.bp-van_ak.UPF",
                 "C.pbe-mt_gipaw.UPF",
                 "C.pbe-rrkjus.UPF",
                 "C.pbe-van_ak.UPF",
                 "C.pbe-van_bm.UPF",
                 "C.pw91-van_ak.UPF",
                 "C.pz-rrkjus.UPF",
                 "C.pz-van_ak.UPF",
                 "C.pz-vbc.UPF",
                 "C.rel-pz-rrkjus.UPF",
                 "C.star1s-blyp-mt.UPF",
                 "C.star1s-pbe-mt_gipaw.UPF",
                 "C.star1s-pbe-rrkjus.UPF",
                 "C.tpss-mt.UPF",
                )

PSEUDO["Cd"] = (
                 "Cd.pbe-n-van.UPF",
                 "Cd.pw91-n-van.UPF",
                )

PSEUDO["Cl"] = (
                 "Cl.blyp-mt.UPF",
                 "Cl.pbe-n-van.UPF",
                 "Cl.pw91-mt.UPF",
                 "Cl.pz-bhs.UPF",
                )

PSEUDO["Co"] = (
                 "Co.pbe-nd-rrkjus.UPF",
                 "Co.pbe-n-van_gipaw.UPF",
                 "Co.pbe-sp-mt_gipaw.UPF",
                 "Co.pz-nd-rrkjus.UPF",
                 "Co.rel-pz-n-rrkjus.UPF",
                 "Co.star1s-pbe-n-van_gipaw.UPF",
                 "Co.star1s-pbe-sp-mt_gipaw.UPF",
                )

PSEUDO["Cr"] = (
                 "Cr.pbe-sp-van.UPF",
                 "Cr.pw91-sp-van.UPF",
                )

PSEUDO["Cs"] = (
                 "Cs.pbe-mt_bw.UPF",
                )

PSEUDO["Cu"] = (
                 "Cu.blyp-n-van_ak.UPF",
                 "Cu.pbe-d-rrkjus.UPF",
                 "Cu.pbe-n-van_ak.UPF",
                 "Cu.pbe-n-van_gipaw.UPF",
                 "Cu.pw91-n-van_ak.UPF",
                 "Cu.pz-d-rrkjus.UPF",
                 "Cu.pz-n-van_ak.UPF",
                 "Cu.star1s-pbe-n-van_gipaw.UPF",
                )

PSEUDO["Fe"] = (
                 "Fe.blyp-sp-van_ak.UPF",
                 "Fe.blyp-sp-van.UPF",
                 "Fe.bp-sp-van_ak.UPF",
                 "Fe.pbe-nd-rrkjus.UPF",
                 "Fe.pbe-sp-mt_gipaw.UPF",
                 "Fe.pbe-sp-van_ak.UPF",
                 "Fe.pbe-sp-van_mit.UPF",
                 "Fe.pbe-sp-van.UPF",
                 "Fe.pw91-sp-van_ak.UPF",
                 "Fe.pz-nd-rrkjus.UPF",
                 "Fe.pz-sp-van_ak.UPF",
                 "Fe.star1s-pbe-sp-mt_gipaw.UPF",
                )

PSEUDO["F"] = (
                 "F.pbe-n-van.UPF",
                 "F.pw91-n-van.UPF",
                 "F.pz-van_asa.UPF",
                )

PSEUDO["Ga"] = (
                 "Ga.pbe-n-van.UPF",
                 "Ga.pw91-n-van.UPF",
                 "Ga.pz-bhs.UPF",
                )

PSEUDO["Ge"] = (
                 "Ge.pw91-n-van.UPF",
                 "Ge.pz-bhs.UPF",
                 "Ge.tpss-n-mt.UPF",
                )

PSEUDO["H"] = (
                 "H.blyp-van_ak.UPF",
                 "H.blyp-vbc.UPF",
                 "H.bp-van_ak.UPF",
                 "H.pbe-rrkjus.UPF",
                 "H.pbe-van_ak.UPF",
                 "H.pbe-van_bm.UPF",
                 "H.pbe-vbc.UPF",
                 "H.pw91-van_ak.UPF",
                 "H.pz-rrkjus.UPF",
                 "H.pz-van_ak.UPF",
                 "H.pz-vbc_050.UPF",
                 "H.pz-vbc_075.UPF",
                 "H.pz-vbc_125.UPF",
                 "H.pz-vbc_150.UPF",
                 "H.pz-vbc.UPF",
                 "H.tpss-mt.UPF",
                )

PSEUDO["He"] = (
                 "He.pbe-mt_fhi.UPF",
                 "He.pz-mt_fhi.UPF",
                )

PSEUDO["In"] = (
                 "In.pbe-d-rrkjus.UPF",
                 "In.pz-bhs.UPF",
                 "In.pz-d-rrkjus.UPF",
                 "In.pz-n-bhs.UPF",
                )

PSEUDO["I"] = (
                 "I.pbe-mt_bw.UPF",
                )

PSEUDO["Ir"] = (
                 "Ir.pbe-n-rrkjus.UPF",
                 "Ir.pbe-n-van.UPF",
                 "Ir.pw91-n-van.UPF",
                )

PSEUDO["K"] = (
                 "K.blyp-n-mt.UPF",
                 "K.pz-n-vbc.UPF",
                 "K.pz-sp-van.UPF",
                )

PSEUDO["Kr"] = (
                 "Kr.pw91-n-van.UPF",
                )

PSEUDO["La"] = (
                 "La.pbe-nsp-van.UPF",
                 "La.pw91-nsp-van.UPF",
                )

PSEUDO["Li"] = (
                 "Li.blyp-s-mt.UPF",
                 "Li.blyp-s-van_ak.UPF",
                 "Li.bp-s-mt.UPF",
                 "Li.bp-s-van_ak.UPF",
                 "Li.pbe-n-van.UPF",
                 "Li.pbe-s-mt.UPF",
                 "Li.pbe-s-van_ak.UPF",
                 "Li.pw91-n-van.UPF",
                 "Li.pw91-s-mt.UPF",
                 "Li.pw91-s-van_ak.UPF",
                 "Li.pz-n-vbc.UPF",
                 "Li.pz-s-mt.UPF",
                 "Li.pz-s-van_ak.UPF",
                )

PSEUDO["Mg"] = (
                 "Mg.pw91-np-van.UPF",
                 "Mg.pz-bhs.UPF",
                 "Mg.pz-n-vbc.UPF",
                )

PSEUDO["Mn"] = (
                 "Mn.pbe-sp-van_mit.UPF",
                 "Mn.pbe-sp-van.UPF",
                )

PSEUDO["Mo"] = (
                 "Mo.pw91-n-van.UPF",
                )

PSEUDO["Na"] = (
                 "Na.blyp-sp-van_ak.UPF",
                 "Na.bp-sp-van_ak.UPF",
                 "Na.pbe-n-mt_bw.UPF",
                 "Na.pbe-n-van.UPF",
                 "Na.pbe-sp-van_ak.UPF",
                 "Na.pw91-n-mt.UPF",
                 "Na.pw91-n-van.UPF",
                 "Na.pw91-sp-van_ak.UPF",
                 "Na.pz-n-vbc.UPF",
                 "Na.pz-sp-van_ak.UPF",
                )

PSEUDO["N"] = (
                 "N.blyp-mt.UPF",
                 "N.blyp-van_ak.UPF",
                 "N.bp-van_ak.UPF",
                 "N.pbe-rrkjus.UPF",
                 "N.pbe-van_ak.UPF",
                 "N.pbe-van_bm.UPF",
                 "N.pw91-van_ak.UPF",
                 "N.pz-rrkjus.UPF",
                 "N.pz-van_ak.UPF",
                 "N.pz-vbc.UPF",
                 "N.star1s-blyp-mt.UPF",
                 "N.star1s-pbe-rrkjus.UPF",
                 "N.star1s-pbe-van.UPF",
                )

PSEUDO["Nb"] = (
                 "Nb.pbe-nsp-van.UPF",
                 "Nb.pw91-nsp-van.UPF",
                 "Nb.pz-sp-van.UPF",
                )

PSEUDO["Ni"] = (
                 "Ni.pbe-nd-rrkjus.UPF",
                 "Ni.pbe-sp-mt_gipaw.UPF",
                 "Ni.pz-nd-rrkjus.UPF",
                 "Ni.star1s-pbe-sp-mt_gipaw.UPF",
                )

PSEUDO["O"] = (
                 "O.blyp-mt.UPF",
                 "O.blyp-van_ak.UPF",
                 "O.bp-van_ak.UPF",
                 "O.pbe-mt.UPF",
                 "O.pbe-rrkjus.UPF",
                 "O.pbe-van_ak.UPF",
                 "O.pbe-van_bm.UPF",
                 "O.pbe-van_gipaw.UPF",
                 "O.pw91-van_ak.UPF",
                 "O.pz-mt.UPF",
                 "O.pz-rrkjus.UPF",
                 "O.pz-van_ak.UPF",
                 "O.rel-pz-rrkjus.UPF",
                 "O.star1s-pbe-van_gipaw.UPF",
                 "O.tpss-mt.UPF",
                )

PSEUDO["Os"] = (
                 "Os.pbe-n-van.UPF",
                 "Os.pw91-n-van.UPF",
                )

PSEUDO["P"] = (
                 "P.blyp-mt.UPF",
                 "P.blyp-van_ak.UPF",
                 "P.bp-van_ak.UPF",
                 "P.pbe-n-van.UPF",
                 "P.pbe-van_ak.UPF",
                 "P.pw91-n-van.UPF",
                 "P.pw91-van_ak.UPF",
                 "P.pz-bhs.UPF",
                 "P.pz-van_ak.UPF",
                )

PSEUDO["Pb"] = (
                 "Pb.pbe-d-van.UPF",
                 "Pb.pz-bhs.UPF",
                 "Pb.pz-d-van.UPF",
                )

PSEUDO["Pd"] = (
                 "Pd.pbe-nd-rrkjus.UPF",
                 "Pd.pbe-rrkjus.UPF",
                 "Pd.pz-nd-rrkjus.UPF",
                 "Pd.pz-rrkjus.UPF",
                )

PSEUDO["Pt"] = (
                 "Pt.pbe-nd-rrkjus.UPF",
                 "Pt.pbe-n-van.UPF",
                 "Pt.pw91-n-van.UPF",
                 "Pt.pz-nd-rrkjus.UPF",
                 "Pt.pz-rrkjus.UPF",
                 "Pt.rel-pz-n-rrkjus.UPF",
                )

PSEUDO["Re"] = (
                 "Re.pw91-n-van.UPF",
                )

PSEUDO["Rh"] = (
                 "Rh.pbe-nd-rrkjus.UPF",
                 "Rh.pbe-rrkjus.UPF",
                 "Rh.pz-rrkjus.UPF",
                )

PSEUDO["Ru"] = (
                 "Ru.pbe-n-van.UPF",
                 "Ru.pw91-n-van.UPF",
                )

PSEUDO["S"] = (
                 "S.blyp-mt.UPF",
                 "S.blyp-van_ak.UPF",
                 "S.bp-van_ak.UPF",
                 "S.pbe-van_bm.UPF",
                 "S.pw91-n-mt.UPF",
                 "S.pw91-van_ak.UPF",
                 "S.pz-bhs.UPF",
                 "S.pz-van_ak.UPF",
                )

PSEUDO["Sb"] = (
                 "Sb.pw91-n-van.UPF",
                 "Sb.pz-bhs.UPF",
                )

PSEUDO["Sc"] = (
                 "Sc.pbe-nsp-van.UPF",
                 "Sc.pw91-nsp-van.UPF",
                )

PSEUDO["Se"] = (
                 "Se.pbe-van.UPF",
                 "Se.pz-bhs.UPF",
                )

PSEUDO["Si"] = (
                 "Si.pbe-mt_gipaw.UPF",
                 "Si.pbe-n-van.UPF",
                 "Si.pbe-rrkj.UPF",
                 "Si.pbe-van_gipaw.UPF",
                 "Si.pw91-n-van.UPF",
                 "Si.pz-vbc.UPF",
                 "Si.star1s-pbe-mt_gipaw.UPF",
                 "Si.star1s-pbe-van_gipaw.UPF",
                 "Si.tpss-mt.UPF",
                )

PSEUDO["Sn"] = (
                 "Sn.pw91-n-van.UPF",
                 "Sn.pz-bhs.UPF",
                )

PSEUDO["Sr"] = (
                 "Sr.pbe-nsp-van.UPF",
                 "Sr.pbe-sp-van.UPF",
                 "Sr.pw91-nsp-van.UPF",
                )

PSEUDO["Ta"] = (
                 "Ta.pbe-nsp-van.UPF",
                 "Ta.pw91-nsp-van.UPF",
                )

PSEUDO["Te"] = (
                 "Te.pbe-rrkj.UPF",
                 "Te.pz-bhs.UPF",
                )

PSEUDO["Ti"] = (
                 "Ti.blyp-sp-van_ak.UPF",
                 "Ti.bp-sp-van_ak.UPF",
                 "Ti.pbe-sp-van_ak.UPF",
                 "Ti.pw91-nsp-van.UPF",
                 "Ti.pw91-sp-van_ak.UPF",
                 "Ti.pz-sp-van_ak.UPF",
                 "Ti.pz-sp-van.UPF",
                )

PSEUDO["Tl"] = (
                 "Tl.pz-d-van.UPF",
                )

PSEUDO["V"] = (
                 "V.pbe-n-van.UPF",
                 "V.pbe-sp-van.UPF",
                )

PSEUDO["W"] = (
                 "W.pbe-nsp-van.UPF",
                 "W.pw91-nsp-van.UPF",
                 "W.pz-bhs.UPF",
                )

PSEUDO["Xe"] = (
                 "Xe.pw91-n-van.UPF",
                )

PSEUDO["Y"] = (
                 "Y.pbe-nsp-van.UPF",
                 "Y.pw91-nsp-van.UPF",
                )

PSEUDO["Zn"] = (
                 "Zn.blyp-van_ak.UPF",
                 "Zn.bp-van_ak.UPF",
                 "Zn.pbe-van.UPF",
                 "Zn.pw91-n-van.UPF",
                 "Zn.pw91-van_ak.UPF",
                 "Zn.pz-van_ak.UPF",
                )

PSEUDO["Zr"] = (
                 "Zr.pbe-nsp-van.UPF",
                 "Zr.pw91-nsp-van.UPF",
                 "Zr.pw91-sp-rrkjus.UPF",
                )

